# url 수집 후 전처리

In [ ]:
import pandas as pd

df = pd.read_csv("youtube_urls.csv")

In [ ]:
df.head()

,category_ko,category_en,code_lang,query,url,video_id
0,BFS,BFS,python,BFS 너비 우선 탐색 강의 설명 site:youtube.com -shorts 파이썬,https://www.youtube.com/watch?v=BsYbdUnKZ-Y,BsYbdUnKZ-Y
1,BFS,BFS,python,BFS 너비 우선 탐색 강의 설명 site:youtube.com -shorts 파이썬,https://www.youtube.com/watch?v=bTMV-VeaTws,bTMV-VeaTws
2,BFS,BFS,python,BFS 너비 우선 탐색 강의 설명 site:youtube.com -shorts 파이썬,https://www.youtube.com/watch?v=9aHVA7mJcqQ,9aHVA7mJcqQ
3,BFS,BFS,python,BFS 너비 우선 탐색 강의 설명 site:youtube.com -shorts 파이썬,https://www.youtube.com/watch?v=naZB_PZ1lb0,naZB_PZ1lb0
4,BFS,BFS,python,BFS 너비 우선 탐색 강의 설명 site:youtube.com -shorts 파이썬,https://www.youtube.com/watch?v=Cm3-AxNsQWg,Cm3-AxNsQWg

In [ ]:
df = df.drop(columns=['category_en'])
print("The 'category_en' column has been dropped.")

The 'category_en' column has been dropped.

In [ ]:
print("Unique values in 'category_ko' column:")
display(df['category_ko'].unique())

Unique values in 'category_ko' column:

array(['BFS', 'DFS', 'DP', 'Greedy', 'Binary Search', 'Two Pointers',
       'Sliding Window', 'Hashing', 'Sorting', 'Stack', 'Queue', 'Heap',
       'Backtracking', 'Bitmask', 'Math', 'Prefix Sum', 'Dijkstra',
       'Shortest Path', 'Topological Sort', 'Divide and Conquer',
       'Parsing', 'String', 'Graph', 'Tree'], dtype=object)

In [ ]:
len(df)

2781

In [ ]:
if df['video_id'].is_unique:
    print("The 'video_id' column is unique.")
else:
    print("The 'video_id' column is NOT unique.")

The 'video_id' column is unique.

In [ ]:
df.head()

,category,code_lang,query,url,video_id
0,BFS,python,BFS 너비 우선 탐색 강의 설명 site:youtube.com -shorts 파이썬,https://www.youtube.com/watch?v=BsYbdUnKZ-Y,BsYbdUnKZ-Y
1,BFS,python,BFS 너비 우선 탐색 강의 설명 site:youtube.com -shorts 파이썬,https://www.youtube.com/watch?v=bTMV-VeaTws,bTMV-VeaTws
2,BFS,python,BFS 너비 우선 탐색 강의 설명 site:youtube.com -shorts 파이썬,https://www.youtube.com/watch?v=9aHVA7mJcqQ,9aHVA7mJcqQ
3,BFS,python,BFS 너비 우선 탐색 강의 설명 site:youtube.com -shorts 파이썬,https://www.youtube.com/watch?v=naZB_PZ1lb0,naZB_PZ1lb0
4,BFS,python,BFS 너비 우선 탐색 강의 설명 site:youtube.com -shorts 파이썬,https://www.youtube.com/watch?v=Cm3-AxNsQWg,Cm3-AxNsQWg

In [ ]:
category_lang_counts = df.groupby(['category', 'code_lang']).size().reset_index(name='count')
display(category_lang_counts)

        category code_lang  count
0            BFS         c     18
1            BFS       cpp     22
2            BFS      java     33
3            BFS    python     41
4   Backtracking         c     27
..           ...       ...    ...
91          Tree    python     44
92  Two Pointers         c     24
93  Two Pointers       cpp     24
94  Two Pointers      java     20
95  Two Pointers    python     27

[96 rows x 3 columns]

In [ ]:
category_lang_counts.to_csv('category_lang_counts.csv', index=False)
print("DataFrame 'category_lang_counts' saved to 'category_lang_counts.csv'")

DataFrame 'category_lang_counts' saved to 'category_lang_counts.csv'

In [ ]:
df = df.rename(columns={'category_ko': 'category'})
print("Column 'category_ko' has been renamed to 'category'.")

Column 'category_ko' has been renamed to 'category'.

In [ ]:
df = df.drop(columns=['query'])

In [ ]:
df.to_csv('youtube_urls_cleaned.csv', index=False)
print("DataFrame 'df' saved to 'youtube_urls_cleaned.csv'")

DataFrame 'df' saved to 'youtube_urls_cleaned.csv'

# 번역 후 전처리

In [ ]:
df_tran = pd.read_csv("youtube_transcripts.csv")

In [ ]:
df_tran.head()

,category,code_lang,url,video_id,transcript,source,error
0,BFS,python,https://www.youtube.com/watch?v=BsYbdUnKZ-Y,BsYbdUnKZ-Y,최근에 한국 드라마가 전세계적으로 인기를 끌고 있는데 여러분은 드라마 볼 때 어떤 ...,whisper,NaN
1,BFS,python,https://www.youtube.com/watch?v=bTMV-VeaTws,bTMV-VeaTws,안녕하세요 오늘은 프로그램 스코딩 테스트 준비 문제 중에 위장이라는 문제를 같이 한...,whisper,NaN
2,BFS,python,https://www.youtube.com/watch?v=9aHVA7mJcqQ,9aHVA7mJcqQ,네 다음은 완전탐색의 기본 코드에 대해 알아보겠습니다. 사실 완전탐색 코드는 정해진...,whisper,NaN
3,BFS,python,https://www.youtube.com/watch?v=naZB_PZ1lb0,naZB_PZ1lb0,안녕하세요 yt 편의점 문허박사 입니다 bfs 첫번째 노드의 거리 프리해 보도록 하...,whisper,NaN
4,BFS,python,https://www.youtube.com/watch?v=Cm3-AxNsQWg,Cm3-AxNsQWg,코딩 테스트 준비를 위한 DFS에 대해서 알아보겠습니다. DFS는 Depth-for...,whisper,NaN

In [ ]:
# error 컬럼에 값이 없는 row
df_tran_no_error = df_tran[df_tran['error'].isna()]

In [ ]:
len(df_tran_no_error)

540

In [ ]:
df_tran_no_error.head()

,category,code_lang,url,video_id,transcript,source,error
0,BFS,python,https://www.youtube.com/watch?v=BsYbdUnKZ-Y,BsYbdUnKZ-Y,최근에 한국 드라마가 전세계적으로 인기를 끌고 있는데 여러분은 드라마 볼 때 어떤 ...,whisper,NaN
1,BFS,python,https://www.youtube.com/watch?v=bTMV-VeaTws,bTMV-VeaTws,안녕하세요 오늘은 프로그램 스코딩 테스트 준비 문제 중에 위장이라는 문제를 같이 한...,whisper,NaN
2,BFS,python,https://www.youtube.com/watch?v=9aHVA7mJcqQ,9aHVA7mJcqQ,네 다음은 완전탐색의 기본 코드에 대해 알아보겠습니다. 사실 완전탐색 코드는 정해진...,whisper,NaN
3,BFS,python,https://www.youtube.com/watch?v=naZB_PZ1lb0,naZB_PZ1lb0,안녕하세요 yt 편의점 문허박사 입니다 bfs 첫번째 노드의 거리 프리해 보도록 하...,whisper,NaN
4,BFS,python,https://www.youtube.com/watch?v=Cm3-AxNsQWg,Cm3-AxNsQWg,코딩 테스트 준비를 위한 DFS에 대해서 알아보겠습니다. DFS는 Depth-for...,whisper,NaN

In [ ]:
df_tran_no_error.to_csv('youtube_transcripts_cleaned.csv', index=False)
print("DataFrame 'df_tran_no_error' saved to 'youtube_transcripts_cleaned.csv'")

DataFrame 'df_tran_no_error' saved to 'youtube_transcripts_cleaned.csv'

In [ ]:
df_tran_no_error = pd.read_csv("youtube_transcripts_cleaned.csv")

In [ ]:
# transcript 컬럼에 값이 없는 row 삭제
df_tran_no = df_tran_no_error.dropna(subset=['transcript'])

In [ ]:
len(df_tran_no)

539

In [ ]:
# Re-initialize df_tran_no from df_tran_no_error after dropping NaNs
df_tran_no = df_tran_no_error.dropna(subset=['transcript'])

# Install langdetect if not already installed (run once per session)
try:
    import langdetect
except ImportError:
    !pip install langdetect
    import langdetect

from langdetect import detect, DetectorFactory
# Ensure consistent results for langdetect
DetectorFactory.seed = 0

def detect_language(text):
    try:
        return detect(text)
    except:
        return 'unknown' # Handle cases where language detection might fail (e.g., very short strings or errors)

# Apply language detection to the 'transcript' column
df_tran_no['detected_lang'] = df_tran_no['transcript'].apply(detect_language)

# Filter out rows where the detected language is not Korean ('ko') or English ('en')
df_tran_no = df_tran_no[df_tran_no['detected_lang'].isin(['ko', 'en'])]

print(f"Number of rows after filtering by detected language: {len(df_tran_no)}")

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 14.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=fc7ceac3520ad78714fdabfe6b45963b4c65b2efb5c34f6628778d4ba91b8865
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9
Number of rows after filtering by detected language: 486

/tmp/ipython-input-1955968860.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tran_no['detected_lang'] = df_tran_no['transcript'].apply(detect_language)

In [ ]:
len(df_tran_no)

486

In [ ]:
# csv 로 저장
df_tran_no.to_csv('youtube_transcripts_cleaned.csv', index=False)
print("DataFrame 'df_tran_no' saved to 'youtube_transcripts_cleaned.csv'")

DataFrame 'df_tran_no' saved to 'youtube_transcripts_cleaned.csv'

# summary 후 전처리

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("youtube_summaries.csv")

In [ ]:
df.head()

,category,code_lang,url,video_id,transcript,source,error,detected_lang,algo_gt_summary,summary_error
0,BFS,python,https://www.youtube.com/watch?v=BsYbdUnKZ-Y,BsYbdUnKZ-Y,최근에 한국 드라마가 전세계적으로 인기를 끌고 있는데 여러분은 드라마 볼 때 어떤 ...,whisper,NaN,ko,"{""version"": ""algo_gt_v1"", ""overall"": {""topic"":...",NaN
1,BFS,python,https://www.youtube.com/watch?v=bTMV-VeaTws,bTMV-VeaTws,안녕하세요 오늘은 프로그램 스코딩 테스트 준비 문제 중에 위장이라는 문제를 같이 한...,whisper,NaN,ko,"{""version"": ""algo_gt_v1"", ""overall"": {""topic"":...",NaN
2,BFS,python,https://www.youtube.com/watch?v=9aHVA7mJcqQ,9aHVA7mJcqQ,네 다음은 완전탐색의 기본 코드에 대해 알아보겠습니다. 사실 완전탐색 코드는 정해진...,whisper,NaN,ko,"{""version"": ""algo_gt_v1"", ""overall"": {""topic"":...",NaN
3,BFS,python,https://www.youtube.com/watch?v=naZB_PZ1lb0,naZB_PZ1lb0,안녕하세요 yt 편의점 문허박사 입니다 bfs 첫번째 노드의 거리 프리해 보도록 하...,whisper,NaN,ko,"{""version"": ""algo_gt_v1"", ""overall"": {""topic"":...",NaN
4,BFS,python,https://www.youtube.com/watch?v=Cm3-AxNsQWg,Cm3-AxNsQWg,코딩 테스트 준비를 위한 DFS에 대해서 알아보겠습니다. DFS는 Depth-for...,whisper,NaN,ko,"{""version"": ""algo_gt_v1"", ""overall"": {""topic"":...",NaN

In [ ]:
df.drop(columns=['video_id', 'source', 'detected_lang', 'error'], inplace=True)

In [ ]:
df.head()

,category,code_lang,url,transcript,algo_gt_summary,summary_error
0,BFS,python,https://www.youtube.com/watch?v=BsYbdUnKZ-Y,최근에 한국 드라마가 전세계적으로 인기를 끌고 있는데 여러분은 드라마 볼 때 어떤 ...,"{""version"": ""algo_gt_v1"", ""overall"": {""topic"":...",NaN
1,BFS,python,https://www.youtube.com/watch?v=bTMV-VeaTws,안녕하세요 오늘은 프로그램 스코딩 테스트 준비 문제 중에 위장이라는 문제를 같이 한...,"{""version"": ""algo_gt_v1"", ""overall"": {""topic"":...",NaN
2,BFS,python,https://www.youtube.com/watch?v=9aHVA7mJcqQ,네 다음은 완전탐색의 기본 코드에 대해 알아보겠습니다. 사실 완전탐색 코드는 정해진...,"{""version"": ""algo_gt_v1"", ""overall"": {""topic"":...",NaN
3,BFS,python,https://www.youtube.com/watch?v=naZB_PZ1lb0,안녕하세요 yt 편의점 문허박사 입니다 bfs 첫번째 노드의 거리 프리해 보도록 하...,"{""version"": ""algo_gt_v1"", ""overall"": {""topic"":...",NaN
4,BFS,python,https://www.youtube.com/watch?v=Cm3-AxNsQWg,코딩 테스트 준비를 위한 DFS에 대해서 알아보겠습니다. DFS는 Depth-for...,"{""version"": ""algo_gt_v1"", ""overall"": {""topic"":...",NaN

In [ ]:
# summary_error 값이 있는 row 확인
df[df['summary_error'].notna()]

Empty DataFrame
Columns: [category, code_lang, url, transcript, algo_gt_summary, summary_error]
Index: []

In [ ]:
df.drop(columns=['summary_error'], inplace=True)

In [ ]:
def json_load(summary_str):
    try:
        summary_dict = json.loads(summary_str)
        return summary_dict
    except (json.JSONDecodeError, AttributeError):
        return None

In [ ]:
import json

print("Displaying full JSON content from 'algo_gt_summary' for the first 3 rows:")
for i in range(3):
    if i < len(df):
        # Ensure the content is treated as a dictionary before dumping
        json_content = df.loc[i, 'algo_gt_summary']
        if isinstance(json_content, dict):
            print(f"\n--- Row {i} ---")
            print(json.dumps(json_content, indent=4, ensure_ascii=False))
        else:
            print(f"\n--- Row {i} ---")
            print(f"Content is not a dictionary: {json_content}")
    else:
        break

Displaying full JSON content from 'algo_gt_summary' for the first 3 rows:

--- Row 0 ---
Content is not a dictionary: {"version": "algo_gt_v1", "overall": {"topic": "DFS와 BFS 알고리즘", "algorithm_name": "깊이 우선 탐색(DFS), 너비 우선 탐색(BFS)", "problem_pattern": "경로 탐색, 네트워크 문제, 조합 생성", "one_liner": "DFS는 깊이 우선으로 탐색하고, BFS는 너비 우선으로 탐색하는 그래프 탐색 알고리즘이다.", "key_terms": ["DFS", "BFS", "그래프 탐색", "재귀", "큐"]}, "axes": {"core_concepts": {"status": "present", "summary": "DFS는 한 경로를 끝까지 탐색하고, BFS는 여러 경로를 동시에 탐색한다.", "must_understand": ["DFS의 재귀적 구현", "BFS의 큐 사용"], "common_misconceptions": []}, "algorithm_flow": {"status": "present", "summary": "DFS는 재귀를 통해 깊이 있게 탐색하고, BFS는 큐를 통해 순차적으로 탐색한다.", "critical_decisions": ["재귀 호출 시 인덱스 증가", "큐에서 요소 꺼내기"], "stop_conditions": ["목표에 도달 시", "모든 경로 탐색 완료 시"]}, "when_to_use": {"status": "present", "summary": "문제의 구조에 따라 DFS 또는 BFS를 선택한다.", "signals": ["경로 탐색 문제", "네트워크 연결 확인"], "prerequisites": ["문제 유형 파악", "알고리즘 이해"]}, "when_not_to_use": {"status": "present", "summary": "DFS는 시간 초과 위험이 있고, BFS는 메모리 사용이 많을 수 있다.", "anti_signals": ["문제가 복잡하여 DFS가 비효율적일 때", "메모리 제한이 있을 때"], "failure_modes": []}, "complexity": {"status": "insufficient_evidence", "time": null, "space": null, "bottlenecks": []}, "examples": {"status": "present", "summary": "DFS는 타겟넘버 문제, BFS는 여행경로 문제에서 사용된다.", "problem_types": ["경로 탐색", "네트워크 문제", "조합 생성"], "bridge_to_code": ["재귀 함수 구현", "큐 사용"]}}, "evaluation_ready_hints": {"must_mention_terms": ["DFS", "BFS", "재귀", "큐", "그래프 탐색"], "minimum_user_summary_requirements": ["DFS와 BFS의 차이", "각 알고리즘의 사용 사례", "구현 방법"], "recommended_next_video_focus": []}, "meta": {"created_at": "2026-01-01T08:25:55.276126+00:00"}}

--- Row 1 ---
Content is not a dictionary: {"version": "algo_gt_v1", "overall": {"topic": "위장 문제", "algorithm_name": "조합 계산", "problem_pattern": "조합 문제", "one_liner": "의상의 종류별 조합을 계산하여 최소 1개 이상 착용하는 경우의 수를 구하는 문제.", "key_terms": ["조합", "의상", "해시맵", "카운터", "리듀스"]}, "axes": {"core_concepts": {"status": "present", "summary": "의상의 종류별로 조합을 계산하고, 입지 않는 경우를 포함하여 최소 1개 이상 착용해야 함.", "must_understand": ["조합의 정의", "입지 않는 경우 추가", "최소 착용 조건"], "common_misconceptions": []}, "algorithm_flow": {"status": "present", "summary": "의상을 종류별로 분류하고, 조합을 계산한 후 최소 착용 조건을 적용.", "critical_decisions": ["종류별 분류", "입지 않는 경우 추가", "최소 착용 조건 적용"], "stop_conditions": ["모든 의상 조합 계산 완료"]}, "when_to_use": {"status": "present", "summary": "의상의 조합을 계산할 때 사용하며, 최소 1개 이상 착용해야 하는 경우.", "signals": ["조합 문제", "의상 종류가 여러 개"], "prerequisites": ["의상 데이터 구조 이해", "조합 계산 개념"]}, "when_not_to_use": {"status": "present", "summary": "입지 않는 경우가 허용되지 않거나 조합이 필요 없는 경우.", "anti_signals": ["단일 의상 착용", "입지 않는 경우 허용"], "failure_modes": []}, "complexity": {"status": "insufficient_evidence", "time": null, "space": null, "bottlenecks": []}, "examples": {"status": "present", "summary": "헤드기어와 아이웨어의 조합을 통해 가능한 경우의 수를 계산.", "problem_types": ["조합 문제", "의상 조합"], "bridge_to_code": ["해시맵 사용", "카운터 사용", "리듀스 함수 사용"]}}, "evaluation_ready_hints": {"must_mention_terms": ["조합", "의상 종류", "입지 않는 경우"], "minimum_user_summary_requirements": ["조합 계산 방법", "입지 않는 경우 처리", "최소 착용 조건 설명"], "recommended_next_video_focus": []}, "meta": {"created_at": "2026-01-01T08:26:06.844545+00:00"}}

--- Row 2 ---
Content is not a dictionary: {"version": "algo_gt_v1", "overall": {"topic": "완전탐색 및 순열 구현", "algorithm_name": "완전탐색, Next Permutation", "problem_pattern": "카드 조합, 순열 찾기", "one_liner": "완전탐색을 통한 카드 조합 문제와 Next Permutation을 이용한 순열 찾기 방법을 설명한다.", "key_terms": ["완전탐색", "순열", "Next Permutation", "시간 복잡도", "이중 포문"]}, "axes": {"core_concepts": {"status": "present", "summary": "완전탐색은 모든 경우를 탐색하는 방법으로, 이중 포문을 사용하여 카드 조합을 찾는다.", "must_understand": ["완전탐색의 정의", "이중 포문의 사용법", "Next Permutation의 개념"], "common_misconceptions": []}, "algorithm_flow": {"status": "present", "summary": "이중 포문을 통해 카드 조합을 찾고, do while 문을 통해 순열을 생성한다.", "critical_decisions": ["포문 변수 초기화", "Count 변수 사용"], "stop_conditions": ["m번째 순열 도달", "모든 순열 출력 완료"]}, "when_to_use": {"status": "present", "summary": "N이 작을 때 완전탐색을 사용하고, 순열 문제에서 Next Permutation을 활용한다.", "signals": ["문제의 크기", "조합 또는 순열 필요성"], "prerequisites": ["N의 크기 이해", "문제의 요구사항 파악"]}, "when_not_to_use": {"status": "present", "summary": "N이 커질 경우 시간 초과가 발생하므로 사용하지 않는다.", "anti_signals": ["N이 10 이상일 때", "1초 제한 문제"], "failure_modes": []}, "complexity": {"status": "present", "time": "O(n!)", "space": null, "bottlenecks": ["N이 커질 때 시간 초과"]}, "examples": {"status": "present", "summary": "포커 카드 조합과 n개의 정수 순열 문제를 예로 든다.", "problem_types": ["조합 문제", "순열 문제"], "bridge_to_code": ["이중 포문 코드", "do while 문 코드"]}}, "evaluation_ready_hints": {"must_mention_terms": ["완전탐색", "Next Permutation", "시간 복잡도"], "minimum_user_summary_requirements": ["완전탐색의 정의", "이중 포문 사용법", "Next Permutation의 개념"], "recommended_next_video_focus": []}, "meta": {"created_at": "2026-01-01T08:26:18.185348+00:00"}}

This output shows the complete JSON structure for the first three entries in the `algo_gt_summary_dict` column. You can see the `version`, `overall` (with its nested fields like `topic`, `category_ko`, etc.), and `sections` fields. If you want to explore specific parts further, let me know!

In [ ]:
 json_content = df.loc[i, 'algo_gt_summary']

In [ ]:
json_content

'{"version": "algo_gt_v1", "overall": {"topic": "DFS와 BFS 알고리즘", "algorithm_name": "깊이 우선 탐색(DFS), 너비 우선 탐색(BFS)", "problem_pattern": "경로 탐색, 네트워크 문제, 조합 생성", "one_liner": "DFS는 깊이 우선으로 탐색하고, BFS는 너비 우선으로 탐색하는 그래프 탐색 알고리즘이다.", "key_terms": ["DFS", "BFS", "그래프 탐색", "재귀", "큐"]}, "axes": {"core_concepts": {"status": "present", "summary": "DFS는 한 경로를 끝까지 탐색하고, BFS는 여러 경로를 동시에 탐색한다.", "must_understand": ["DFS의 재귀적 구현", "BFS의 큐 사용"], "common_misconceptions": []}, "algorithm_flow": {"status": "present", "summary": "DFS는 재귀를 통해 깊이 있게 탐색하고, BFS는 큐를 통해 순차적으로 탐색한다.", "critical_decisions": ["재귀 호출 시 인덱스 증가", "큐에서 요소 꺼내기"], "stop_conditions": ["목표에 도달 시", "모든 경로 탐색 완료 시"]}, "when_to_use": {"status": "present", "summary": "문제의 구조에 따라 DFS 또는 BFS를 선택한다.", "signals": ["경로 탐색 문제", "네트워크 연결 확인"], "prerequisites": ["문제 유형 파악", "알고리즘 이해"]}, "when_not_to_use": {"status": "present", "summary": "DFS는 시간 초과 위험이 있고, BFS는 메모리 사용이 많을 수 있다.", "anti_signals": ["문제가 복잡하여 DFS가 비효율적일 때", "메모리 제한이 있을 때"], "failure_modes": []}, "complexity": {"status": "insufficient_evidence", "time": null, "space": null, "bottlenecks": []}, "examples": {"status": "present", "summary": "DFS는 타겟넘버 문제, BFS는 여행경로 문제에서 사용된다.", "problem_types": ["경로 탐색", "네트워크 문제", "조합 생성"], "bridge_to_code": ["재귀 함수 구현", "큐 사용"]}}, "evaluation_ready_hints": {"must_mention_terms": ["DFS", "BFS", "재귀", "큐", "그래프 탐색"], "minimum_user_summary_requirements": ["DFS와 BFS의 차이", "각 알고리즘의 사용 사례", "구현 방법"], "recommended_next_video_focus": []}, "meta": {"created_at": "2026-01-01T08:25:55.276126+00:00"}}'

In [ ]:
# json_content key value 값 확인
json_content.keys()

AttributeError: 'str' object has no attribute 'keys'

In [ ]:
df_texts=pd.read_csv("youtube_summaries_texts.csv")

In [ ]:
df_texts.head()

,category,code_lang,url,video_id,transcript,source,error,detected_lang,algo_gt_summary,summary_error
0,BFS,python,https://www.youtube.com/watch?v=BsYbdUnKZ-Y,BsYbdUnKZ-Y,최근에 한국 드라마가 전세계적으로 인기를 끌고 있는데 여러분은 드라마 볼 때 어떤 ...,whisper,NaN,ko,"DFS(깊이 우선 탐색)와 BFS(너비 우선 탐색)는 그래프 탐색 알고리즘으로, 각...",NaN
1,BFS,python,https://www.youtube.com/watch?v=bTMV-VeaTws,bTMV-VeaTws,안녕하세요 오늘은 프로그램 스코딩 테스트 준비 문제 중에 위장이라는 문제를 같이 한...,whisper,NaN,ko,위장 문제는 스파이가 다양한 의상을 조합하여 위장해야 하는 상황을 다룹니다. 주어진...,NaN
2,BFS,python,https://www.youtube.com/watch?v=9aHVA7mJcqQ,9aHVA7mJcqQ,네 다음은 완전탐색의 기본 코드에 대해 알아보겠습니다. 사실 완전탐색 코드는 정해진...,whisper,NaN,ko,"완전탐색의 기본 코드는 문제에 따라 다양한 형태로 구현될 수 있으며, 여기서는 두 ...",NaN
3,BFS,python,https://www.youtube.com/watch?v=naZB_PZ1lb0,naZB_PZ1lb0,안녕하세요 yt 편의점 문허박사 입니다 bfs 첫번째 노드의 거리 프리해 보도록 하...,whisper,NaN,ko,BFS(너비 우선 탐색) 알고리즘을 사용하여 방향성이 없는 그래프에서 출발 노드에서...,NaN
4,BFS,python,https://www.youtube.com/watch?v=Cm3-AxNsQWg,Cm3-AxNsQWg,코딩 테스트 준비를 위한 DFS에 대해서 알아보겠습니다. DFS는 Depth-for...,whisper,NaN,ko,"깊이 우선 탐색(DFS)은 그래프를 탐색하는 방법으로, 시작 노드에서 깊이 방향으로...",NaN

In [ ]:
df_texts.drop(columns=['source', 'error', 'detected_lang', 'summary_error'], inplace=True)

In [ ]:
df_texts.head()

,category,code_lang,url,video_id,transcript,algo_gt_summary
0,BFS,python,https://www.youtube.com/watch?v=BsYbdUnKZ-Y,BsYbdUnKZ-Y,최근에 한국 드라마가 전세계적으로 인기를 끌고 있는데 여러분은 드라마 볼 때 어떤 ...,"DFS(깊이 우선 탐색)와 BFS(너비 우선 탐색)는 그래프 탐색 알고리즘으로, 각..."
1,BFS,python,https://www.youtube.com/watch?v=bTMV-VeaTws,bTMV-VeaTws,안녕하세요 오늘은 프로그램 스코딩 테스트 준비 문제 중에 위장이라는 문제를 같이 한...,위장 문제는 스파이가 다양한 의상을 조합하여 위장해야 하는 상황을 다룹니다. 주어진...
2,BFS,python,https://www.youtube.com/watch?v=9aHVA7mJcqQ,9aHVA7mJcqQ,네 다음은 완전탐색의 기본 코드에 대해 알아보겠습니다. 사실 완전탐색 코드는 정해진...,"완전탐색의 기본 코드는 문제에 따라 다양한 형태로 구현될 수 있으며, 여기서는 두 ..."
3,BFS,python,https://www.youtube.com/watch?v=naZB_PZ1lb0,naZB_PZ1lb0,안녕하세요 yt 편의점 문허박사 입니다 bfs 첫번째 노드의 거리 프리해 보도록 하...,BFS(너비 우선 탐색) 알고리즘을 사용하여 방향성이 없는 그래프에서 출발 노드에서...
4,BFS,python,https://www.youtube.com/watch?v=Cm3-AxNsQWg,Cm3-AxNsQWg,코딩 테스트 준비를 위한 DFS에 대해서 알아보겠습니다. DFS는 Depth-for...,"깊이 우선 탐색(DFS)은 그래프를 탐색하는 방법으로, 시작 노드에서 깊이 방향으로..."

In [ ]:
df_texts['algo_gt_summary'][0]

'DFS(깊이 우선 탐색)와 BFS(너비 우선 탐색)는 그래프 탐색 알고리즘으로, 각각의 특징에 따라 문제를 해결하는 방식이 다릅니다. DFS는 한 경로를 끝까지 탐색한 후 다른 경로로 이동하는 방식으로, 재귀함수를 통해 구현됩니다. 예를 들어, 타겟넘버 문제에서는 주어진 숫자들을 더하거나 빼서 목표 숫자를 만드는 모든 경우를 탐색합니다. 반면, BFS는 여러 경로를 동시에 탐색하며 큐를 사용하여 순서대로 처리합니다. 여행경로 문제에서 모든 항공권을 활용하는 경로를 찾는 데 적합합니다.\n\nDFS는 동작 검증이 용이하고 코드가 간결해지는 장점이 있지만, 최악의 경우 모든 조합을 탐색해야 할 수 있어 시간이 초과될 위험이 있습니다. BFS는 모든 경우를 한 단계씩 탐색하므로 시간 복잡도가 낮고, 특정 조건에서 더 효율적일 수 있습니다. 문제의 난이도와 유형에 따라 적절한 알고리즘을 선택하는 것이 중요합니다.\n\n- DFS는 재귀함수로 구현하며, 특정 경로를 끝까지 탐색.\n- BFS는 큐를 사용하여 여러 경로를 동시에 탐색.\n- DFS는 동작 검증이 쉽고 코드가 간결하지만, 최악의 경우 시간이 초과될 수 있음.\n- BFS는 시간 복잡도가 낮고, 특정 문제에서 더 효율적일 수 있음.\n- 문제 유형에 따라 DFS와 BFS를 적절히 선택하여 해결하는 것이 중요.'

# 테이블화 전처리

In [18]:
import pandas as pd
df= pd.read_csv("youtube_summaries_texts.csv")

In [19]:
df.head()

,category,code_lang,url,video_id,transcript,source,error,detected_lang,algo_gt_summary,summary_error,categories,llm_code_lang
0,BFS,"[""python"", ""cpp"", ""java"", ""c""]",https://www.youtube.com/watch?v=BsYbdUnKZ-Y,BsYbdUnKZ-Y,최근에 한국 드라마가 전세계적으로 인기를 끌고 있는데 여러분은 드라마 볼 때 어떤 ...,whisper,NaN,ko,"깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS)은 그래프 탐색 알고리즘으로, 각...",NaN,"[""DFS"", ""BFS""]",unknown
1,BFS,"[""python""]",https://www.youtube.com/watch?v=bTMV-VeaTws,bTMV-VeaTws,안녕하세요 오늘은 프로그램 스코딩 테스트 준비 문제 중에 위장이라는 문제를 같이 한...,whisper,NaN,ko,"스파이가 다양한 의상을 조합하여 위장하는 문제를 해결하기 위해, 의상의 종류별로 개...",NaN,"[""HashMap""]",python
2,BFS,"[""cpp""]",https://www.youtube.com/watch?v=9aHVA7mJcqQ,9aHVA7mJcqQ,네 다음은 완전탐색의 기본 코드에 대해 알아보겠습니다. 사실 완전탐색 코드는 정해진...,whisper,NaN,ko,"완전탐색의 기본 코드에 대해 설명하며, 두 가지 예제를 통해 포문과 순열 구현을 다...",NaN,"[""Brute Force""]",unknown
3,BFS,"[""python""]",https://www.youtube.com/watch?v=naZB_PZ1lb0,naZB_PZ1lb0,안녕하세요 yt 편의점 문허박사 입니다 bfs 첫번째 노드의 거리 프리해 보도록 하...,whisper,NaN,ko,BFS(너비 우선 탐색)는 방향성이 없는 그래프에서 출발 노드에서 도착 노드까지의 ...,NaN,"[""BFS""]",unknown
4,BFS,"[""python""]",https://www.youtube.com/watch?v=Cm3-AxNsQWg,Cm3-AxNsQWg,코딩 테스트 준비를 위한 DFS에 대해서 알아보겠습니다. DFS는 Depth-for...,whisper,NaN,ko,"깊이 우선 탐색(DFS)은 그래프를 탐색하는 방법으로, 시작 노드에서 깊이 방향으로...",NaN,"[""DFS"", ""Stack""]",unknown

In [20]:
df.drop(columns=['source', 'error', 'detected_lang', 'summary_error', 'llm_code_lang', 'category','video_id', 'transcript'], inplace=True)

In [21]:
df.head()

,code_lang,url,algo_gt_summary,categories
0,"[""python"", ""cpp"", ""java"", ""c""]",https://www.youtube.com/watch?v=BsYbdUnKZ-Y,"깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS)은 그래프 탐색 알고리즘으로, 각...","[""DFS"", ""BFS""]"
1,"[""python""]",https://www.youtube.com/watch?v=bTMV-VeaTws,"스파이가 다양한 의상을 조합하여 위장하는 문제를 해결하기 위해, 의상의 종류별로 개...","[""HashMap""]"
2,"[""cpp""]",https://www.youtube.com/watch?v=9aHVA7mJcqQ,"완전탐색의 기본 코드에 대해 설명하며, 두 가지 예제를 통해 포문과 순열 구현을 다...","[""Brute Force""]"
3,"[""python""]",https://www.youtube.com/watch?v=naZB_PZ1lb0,BFS(너비 우선 탐색)는 방향성이 없는 그래프에서 출발 노드에서 도착 노드까지의 ...,"[""BFS""]"
4,"[""python""]",https://www.youtube.com/watch?v=Cm3-AxNsQWg,"깊이 우선 탐색(DFS)은 그래프를 탐색하는 방법으로, 시작 노드에서 깊이 방향으로...","[""DFS"", ""Stack""]"

In [22]:
# 102개의 row만 남기기
df.drop(df.index[102:], inplace=True)

In [23]:
df.head()

,code_lang,url,algo_gt_summary,categories
0,"[""python"", ""cpp"", ""java"", ""c""]",https://www.youtube.com/watch?v=BsYbdUnKZ-Y,"깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS)은 그래프 탐색 알고리즘으로, 각...","[""DFS"", ""BFS""]"
1,"[""python""]",https://www.youtube.com/watch?v=bTMV-VeaTws,"스파이가 다양한 의상을 조합하여 위장하는 문제를 해결하기 위해, 의상의 종류별로 개...","[""HashMap""]"
2,"[""cpp""]",https://www.youtube.com/watch?v=9aHVA7mJcqQ,"완전탐색의 기본 코드에 대해 설명하며, 두 가지 예제를 통해 포문과 순열 구현을 다...","[""Brute Force""]"
3,"[""python""]",https://www.youtube.com/watch?v=naZB_PZ1lb0,BFS(너비 우선 탐색)는 방향성이 없는 그래프에서 출발 노드에서 도착 노드까지의 ...,"[""BFS""]"
4,"[""python""]",https://www.youtube.com/watch?v=Cm3-AxNsQWg,"깊이 우선 탐색(DFS)은 그래프를 탐색하는 방법으로, 시작 노드에서 깊이 방향으로...","[""DFS"", ""Stack""]"

In [31]:
df.to_csv('study_recommendation_cleaned.csv', index=False)
print("DataFrame 'df' saved to 'youtube_summaries_texts_cleaned.csv'")

DataFrame 'df' saved to 'youtube_summaries_texts_cleaned.csv'

In [24]:
# domain algorithm 으로 column 추가
df['domain'] = 'algorithm'

In [25]:
df.head()

,code_lang,url,algo_gt_summary,categories,domain
0,"[""python"", ""cpp"", ""java"", ""c""]",https://www.youtube.com/watch?v=BsYbdUnKZ-Y,"깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS)은 그래프 탐색 알고리즘으로, 각...","[""DFS"", ""BFS""]",algorithm
1,"[""python""]",https://www.youtube.com/watch?v=bTMV-VeaTws,"스파이가 다양한 의상을 조합하여 위장하는 문제를 해결하기 위해, 의상의 종류별로 개...","[""HashMap""]",algorithm
2,"[""cpp""]",https://www.youtube.com/watch?v=9aHVA7mJcqQ,"완전탐색의 기본 코드에 대해 설명하며, 두 가지 예제를 통해 포문과 순열 구현을 다...","[""Brute Force""]",algorithm
3,"[""python""]",https://www.youtube.com/watch?v=naZB_PZ1lb0,BFS(너비 우선 탐색)는 방향성이 없는 그래프에서 출발 노드에서 도착 노드까지의 ...,"[""BFS""]",algorithm
4,"[""python""]",https://www.youtube.com/watch?v=Cm3-AxNsQWg,"깊이 우선 탐색(DFS)은 그래프를 탐색하는 방법으로, 시작 노드에서 깊이 방향으로...","[""DFS"", ""Stack""]",algorithm

In [26]:
# url -> video_url
# algo_gt_summary -> summaries
# column 이름 변경
df.rename(columns={'url': 'video_url', 'algo_gt_summary': 'summary'}, inplace=True)

In [30]:
df.head()

,code_lang,video_url,summary,categories,domain
0,"[""python"", ""cpp"", ""java"", ""c""]",https://www.youtube.com/watch?v=BsYbdUnKZ-Y,"깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS)은 그래프 탐색 알고리즘으로, 각...","[""DFS"", ""BFS""]",algorithm
1,"[""python""]",https://www.youtube.com/watch?v=bTMV-VeaTws,"스파이가 다양한 의상을 조합하여 위장하는 문제를 해결하기 위해, 의상의 종류별로 개...","[""HashMap""]",algorithm
2,"[""cpp""]",https://www.youtube.com/watch?v=9aHVA7mJcqQ,"완전탐색의 기본 코드에 대해 설명하며, 두 가지 예제를 통해 포문과 순열 구현을 다...","[""Brute Force""]",algorithm
3,"[""python""]",https://www.youtube.com/watch?v=naZB_PZ1lb0,BFS(너비 우선 탐색)는 방향성이 없는 그래프에서 출발 노드에서 도착 노드까지의 ...,"[""BFS""]",algorithm
4,"[""python""]",https://www.youtube.com/watch?v=Cm3-AxNsQWg,"깊이 우선 탐색(DFS)은 그래프를 탐색하는 방법으로, 시작 노드에서 깊이 방향으로...","[""DFS"", ""Stack""]",algorithm

# data 합치기

In [58]:
# interview_final_data.csv와 sudy_recommendation_cleaned.csv merge
import pandas as pd
df_study = pd.read_csv("final_data.csv")
df_interview = pd.read_csv("interview_final_data.csv")

In [59]:
# 두개를 하나의 table로 합치기
df_study.rename(columns={'categories': 'category'}, inplace=True)
df = pd.concat([df_study, df_interview], ignore_index=True)

In [60]:
df.head()

,code_lang,video_url,summary,category,domain,id
0,"[""python"", ""cpp"", ""java"", ""c""]",https://www.youtube.com/watch?v=BsYbdUnKZ-Y,"깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS)은 그래프 탐색 알고리즘으로, 각...","[""DFS"", ""BFS""]",algorithm,1
1,"[""python""]",https://www.youtube.com/watch?v=46VmSgebZP4,"BFS(너비 우선 탐색) 알고리즘은 그래프를 탐색하는 방법으로, 큐 자료구조를 사용...","[""BFS""]",algorithm,2
2,"[""python""]",https://www.youtube.com/watch?v=e0RBEHvAI_4,이번 강의에서는 그래프 탐색 알고리즘 중 너비 우선 탐색(BFS)에 대해 다룬다. ...,"[""BFS"", ""DFS""]",algorithm,3
3,"[""python""]",https://www.youtube.com/watch?v=U5-bRX2AHNY,"너비 우선 탐색(BFS)은 그래프나 트리를 탐색하는 알고리즘으로, 주어진 노드에서 ...","[""BFS""]",algorithm,4
4,"[""python""]",https://www.youtube.com/watch?v=6T90pTJ03YY,"너비 우선 탐색(BFS) 알고리즘은 그래프의 노드를 탐색하는 방법으로, 시작 노드에...","[""BFS""]",algorithm,5

In [63]:
# df를 final_data2.csv 로 저장
df.to_csv('final_data2.csv', index=False)

In [64]:
#df의 id 컬럼 초기화하고 다시 순서대로 매기기
df = df.reset_index(drop=True)
df['id'] = df.index + 1
df.head()
df.to_csv('final_data2.csv', index=False)
print("DataFrame 'df' saved to 'final_data2.csv' with reset 'id' column.")

DataFrame 'df' saved to 'final_data2.csv' with reset 'id' column.

In [35]:
# id 순서대로 붙이기
df['id'] = range(1, len(df) + 1)

In [61]:
df.head()

,code_lang,video_url,summary,category,domain,id
0,"[""python"", ""cpp"", ""java"", ""c""]",https://www.youtube.com/watch?v=BsYbdUnKZ-Y,"깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS)은 그래프 탐색 알고리즘으로, 각...","[""DFS"", ""BFS""]",algorithm,1
1,"[""python""]",https://www.youtube.com/watch?v=46VmSgebZP4,"BFS(너비 우선 탐색) 알고리즘은 그래프를 탐색하는 방법으로, 큐 자료구조를 사용...","[""BFS""]",algorithm,2
2,"[""python""]",https://www.youtube.com/watch?v=e0RBEHvAI_4,이번 강의에서는 그래프 탐색 알고리즘 중 너비 우선 탐색(BFS)에 대해 다룬다. ...,"[""BFS"", ""DFS""]",algorithm,3
3,"[""python""]",https://www.youtube.com/watch?v=U5-bRX2AHNY,"너비 우선 탐색(BFS)은 그래프나 트리를 탐색하는 알고리즘으로, 주어진 노드에서 ...","[""BFS""]",algorithm,4
4,"[""python""]",https://www.youtube.com/watch?v=6T90pTJ03YY,"너비 우선 탐색(BFS) 알고리즘은 그래프의 노드를 탐색하는 방법으로, 시작 노드에...","[""BFS""]",algorithm,5

In [37]:
# unique한 code_lang 확인
df['code_lang'].unique()

array(['["python", "cpp", "java", "c"]', '["python"]', '["cpp"]',
       '["java"]', 'java', '["cpp","java"]', "['java']", "['c']", '["c"]',
       '["cpp", "java", "python"]', nan], dtype=object)

In [39]:
category = df['category'].unique()

In [40]:
category

array(['["DFS", "BFS"]', '["HashMap"]', '["Brute Force"]', '["BFS"]',
       '["DFS", "Stack"]', '["Graph"]', '["Math","Brute Force"]',
       '["DFS", "BFS", "Graph"]', '["Hashing"]',
       '["BFS", "Dijkstra", "Binary Search"]', '["Math"]',
       '["Sorting", "Hashing"]', '["DFS", "BFS","Graph"]',
       '["BFS", "DFS"]', '["BFS", "Graph"]', '["BFS", "Queue"]', '[]',
       '["Simulation","Array"]', '["Greedy"]', '["Math","Aggregation"]',
       '["Array","Implementation"]', '["Tree","Backtracking"]',
       '["Tree","DFS"]', '["Tree","String"]',
       '["Heap","Queue","Tree","Backtracking"]',
       '["DFS", "BFS","Graph","Tree","Queue","Stack","Backtracking"]',
       '["BFS","Graph"]', '["BFS", "Tree", "Queue"]',
       '["BFS", "Graph", "Queue"]', '["BFS", "Graph", "Queue", "Matrix"]',
       '["BFS", "Graph" ,"Queue"]', '["BFS","Graph","Tree","Queue"]',
       '["BFS","Graph","Queue"]', '["BFS", "DFS", "Graph"]',
       '["DFS","Graph","Stack"]',
       '["DFS", "Graph", "Stack", "Backtracking", "Matrix", "Simulation"]',
       '["DFS", "Graph"]', '["Recursion", "Math"]',
       '["BFS", "Graph", "Queue", "Shortest Path"]',
       '["BFS", "Implementation"]', '["BFS", "DFS", "Implementation"]]',
       '["String","Simulation"]', '["BFS", "Queue", "Graph","Vector"]',
       '["BFS", "Shortest Path"]', '["BFS", "Queue", "Graph"]',
       '["BFS", "Tree", "Graph"]]', '["BFS", "DFS", "Queue", "Stack"]',
       '["BFS", "DFS", "Graph", "Queue", "Stack"]',
       '["BFS", "Graph", "Implementation"]', '["DFS"]',
       '["DFS", "Graph", "Stack"]', '["DP"]', '["DFS", "Backtracking"]',
       '["String"]', '["DFS", "Tree"]', '["DFS","Graph","Tree"]',
       '["DFS","Graph"]', '["DFS","Stack","Tree","Graph"]',
       '["DFS","Graph","Tree","Stack"]', '["DFS", "Stack", "Graph"]',
       'REQUIREMENT_CHECK', 'LOGIC_DESIGN', 'THINK_ALOUD', 'CRISIS_MGMT',
       'CODE_VERIFICATION'], dtype=object)

In [41]:
#'REQUIREMENT_CHECK' -> ['REQUIREMENT_CHECK']
#'LOGIC_DESIGN' -> ['LOGIC_DESIGN']
#'THINK_ALOUD' -> ['THINK_ALOUD']
#'CRISIS_MGMT'-> ['CRISIS_MGMT']
#'CODE_VERIFICATION' -> ['CODE_VERIFICATION'] 로 변환
df['category'] = df['category'].replace('REQUIREMENT_CHECK', "['REQUIREMENT_CHECK']")
df['category'] = df['category'].replace('LOGIC_DESIGN', "['LOGIC_DESIGN']")
df['category'] = df['category'].replace('THINK_ALOUD', "['THINK_ALOUD']")
df['category'] = df['category'].replace('CRISIS_MGMT', "['CRISIS_MGMT']")
df['category'] = df['category'].replace('CODE_VERIFICATION', "['CODE_VERIFICATION']")

In [42]:
df.head()

,code_lang,video_url,summary,category,domain,id
0,"[""python"", ""cpp"", ""java"", ""c""]",https://www.youtube.com/watch?v=BsYbdUnKZ-Y,"깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS)은 그래프 탐색 알고리즘으로, 각...","[""DFS"", ""BFS""]",algorithm,1
1,"[""python""]",https://www.youtube.com/watch?v=bTMV-VeaTws,"스파이가 다양한 의상을 조합하여 위장하는 문제를 해결하기 위해, 의상의 종류별로 개...","[""HashMap""]",algorithm,2
2,"[""cpp""]",https://www.youtube.com/watch?v=9aHVA7mJcqQ,"완전탐색의 기본 코드에 대해 설명하며, 두 가지 예제를 통해 포문과 순열 구현을 다...","[""Brute Force""]",algorithm,3
3,"[""python""]",https://www.youtube.com/watch?v=naZB_PZ1lb0,BFS(너비 우선 탐색)는 방향성이 없는 그래프에서 출발 노드에서 도착 노드까지의 ...,"[""BFS""]",algorithm,4
4,"[""python""]",https://www.youtube.com/watch?v=Cm3-AxNsQWg,"깊이 우선 탐색(DFS)은 그래프를 탐색하는 방법으로, 시작 노드에서 깊이 방향으로...","[""DFS"", ""Stack""]",algorithm,5

In [62]:
df.to_csv('final_data2.csv', index=False)
print("DataFrame 'df' saved to 'final_data2.csv'")

DataFrame 'df' saved to 'final_data2.csv'

In [45]:
#final_data.csv 에서 특정 row 삭제
df = pd.read_csv("final_data.csv")
#code_lang이 java인 row 삭제
df = df[df['code_lang'] != 'java']
df.to_csv('final_data.csv', index=False)
print("DataFrame 'df' saved to 'final_data.csv' after removing rows with code_lang as 'java'")

DataFrame 'df' saved to 'final_data.csv' after removing rows with code_lang as 'java'

In [49]:
# final_data.csv 에서 특정 row 삭제
df = pd.read_csv("final_data.csv")
#전체 row가 빈 row 삭제
df = df.dropna(how='all')
df.to_csv('final_data.csv', index=False)
print("DataFrame 'df' saved to 'final_data.csv' after removing empty rows")

DataFrame 'df' saved to 'final_data.csv' after removing empty rows

In [51]:
# domain 컬럼이 빈 값이면 algorithm 으로 채우기
df = pd.read_csv("final_data.csv")
df['domain'].fillna('algorithm', inplace=True)
df.to_csv('final_data.csv', index=False)
print("DataFrame 'df' saved to 'final_data.csv' after filling empty 'domain' values with 'algorithm'")

DataFrame 'df' saved to 'final_data.csv' after filling empty 'domain' values with 'algorithm'

C:\Users\Playdata\AppData\Local\Temp\ipykernel_1576\3835202221.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['domain'].fillna('algorithm', inplace=True)

In [53]:
# domain 기준으로 domain에 들어간 값이 같은 것끼리 재정렬
df = pd.read_csv("final_data.csv")
df = df.sort_values(by=['domain']).reset_index(drop=True)
# id 값 지우고 다시 순서대로
df = df.drop(columns=['id'])
df.to_csv('final_data.csv', index=False)
print("DataFrame 'df' saved to 'final_data.csv' after sorting by 'domain' and resetting 'id'")

DataFrame 'df' saved to 'final_data.csv' after sorting by 'domain' and resetting 'id'

In [54]:
# domain 컬럼이 livecoding인 경우 category 기준으로 재정렬, 원본 csv 파일을 변경하는거임
df = pd.read_csv("final_data.csv")
df_livecoding = df[df['domain'] == 'livecoding']
df_livecoding = df_livecoding.sort_values(by=['category']).reset_index(drop=True)

In [57]:
# domain이 algorithm인 경우의 row들은 그대로 내버려 두고, domain이 livecoding인 경우의 row들만 category 기준으로 재정렬한 후에 다시 합치기
df_algorithm = df[df['domain'] == 'algorithm']
df_algorithm = df_algorithm.reset_index(drop=True)
df_final = pd.concat([df_algorithm, df_livecoding], ignore_index=True)
# id 다시 붙이기
df_final['id'] = range(1, len(df_final) + 1)
df_final.to_csv('final_data.csv', index=False)
print("DataFrame 'df_final' saved to 'final_data.csv' after merging sorted 'livecoding' and 'algorithm' domains")

# 제대로 된거 맞냐
df_check = pd.read_csv("final_data.csv")
df_check.head()

DataFrame 'df_final' saved to 'final_data.csv' after merging sorted 'livecoding' and 'algorithm' domains

,code_lang,video_url,summary,category,domain,id
0,"[""python"", ""cpp"", ""java"", ""c""]",https://www.youtube.com/watch?v=BsYbdUnKZ-Y,"깊이 우선 탐색(DFS)과 너비 우선 탐색(BFS)은 그래프 탐색 알고리즘으로, 각...","[""DFS"", ""BFS""]",algorithm,1
1,"[""python""]",https://www.youtube.com/watch?v=46VmSgebZP4,"BFS(너비 우선 탐색) 알고리즘은 그래프를 탐색하는 방법으로, 큐 자료구조를 사용...","[""BFS""]",algorithm,2
2,"[""python""]",https://www.youtube.com/watch?v=e0RBEHvAI_4,이번 강의에서는 그래프 탐색 알고리즘 중 너비 우선 탐색(BFS)에 대해 다룬다. ...,"[""BFS"", ""DFS""]",algorithm,3
3,"[""python""]",https://www.youtube.com/watch?v=U5-bRX2AHNY,"너비 우선 탐색(BFS)은 그래프나 트리를 탐색하는 알고리즘으로, 주어진 노드에서 ...","[""BFS""]",algorithm,4
4,"[""python""]",https://www.youtube.com/watch?v=6T90pTJ03YY,"너비 우선 탐색(BFS) 알고리즘은 그래프의 노드를 탐색하는 방법으로, 시작 노드에...","[""BFS""]",algorithm,5

In [65]:
#plutsyoutube_summaries_texts.csv의 code_lang 컬럼안에 []로 감싸진 값이 있는 경우만 추출
df = pd.read_csv("plutsyoutube_summaries_texts.csv")
df = df[df['code_lang'].str.startswith('[') & df['code_lang'].str.endswith(']')]
df.head()

,category,code_lang,url,video_id,transcript,source,error,detected_lang,algo_gt_summary,summary_error,categories,llm_code_lang
102,DFS,"[""python""]",https://www.youtube.com/watch?v=vnjjMVcO-R4,vnjjMVcO-R4,Hello and welcome back to Amulya's Academy You...,whisper,NaN,en,DFS(깊이 우선 탐색) 알고리즘을 사용하여 연결되지 않은 그래프를 탐색하는 방법에...,NaN,"[""DFS"",""Graph"",""Stack""]",unknown
103,DFS,"[""python""]",https://www.youtube.com/watch?v=dqnZShCbQiI,dqnZShCbQiI,Hello guys and welcome to Amulya's Academy You...,whisper,NaN,en,DFS(깊이 우선 탐색) 알고리즘을 반복적인 방식으로 구현하는 방법에 대해 설명한다...,NaN,"[""DFS"",""Graph"",""Stack""]",python
104,DFS,"[""python""]",https://www.youtube.com/watch?v=Sbciimd09h4,Sbciimd09h4,"In this video, we're going to be learning how ...",whisper,NaN,en,"깊이 우선 탐색(DFS)은 트리를 탐색하는 방법으로, 여러 가지 방식(전위, 중위,...",NaN,"[""DFS"",""Stack"",""Tree""]",python
105,DFS,"[""python""]",https://www.youtube.com/watch?v=QUlkiLgFdHU,QUlkiLgFdHU,Hello guys and welcome to Amulya's Academy You...,whisper,NaN,en,"그래프 탐색은 그래프의 모든 노드를 방문하는 과정을 의미하며, 이 강의에서는 깊이 ...",NaN,"[""DFS"", ""Graph"",""Backtracking"",""Tree""]",unknown
106,DFS,"[""python""]",https://www.youtube.com/watch?v=X378u6fEfQU,X378u6fEfQU,hello everyone and welcome to coding card so i...,whisper,NaN,en,"깊이 우선 탐색(DFS)은 그래프의 모든 노드를 탐색하는 알고리즘으로, 주어진 노드...",NaN,"[""DFS"", ""Stack"", ""Graph""]",unknown

In [68]:
#plutsyoutube_summaries_texts.csv를 final_data2.csv에 병합하기 위해 형식을 final_data2.csv에 맞추기
df_pluts = pd.read_csv("plutsyoutube_summaries_texts.csv")
df_pluts = df_pluts.drop(columns=['source', 'error', 'detected_lang', 'summary_error', 'llm_code_lang', 'transcript'])
df_pluts.rename(columns={'url': 'video_url', 'algo_gt_summary': 'summary'}, inplace=True)
df_pluts.head()
# 앞서 추출한 것들을 final_data2.csv에 병합 하면서 새롭게 final_data3.csv 만들기
df_final_data2 = pd.read_csv("final_data2.csv")
df_merged = pd.concat([df_final_data2, df_pluts], ignore_index=True)
df_merged.to_csv('final_data3.csv', index=False)    
print("DataFrame 'df_merged' saved to 'final_data3.csv'")

DataFrame 'df_merged' saved to 'final_data3.csv'

In [69]:
# final_data3.csv 에서 code_lang이 값이 있으면서 []로 감싸진 값이 아닌 row들 삭제
df_final_data3 = pd.read_csv("final_data3.csv")
df_final_data3 = df_final_data3[df_final_data3['code_lang'].isnull() | (df_final_data3['code_lang'].str.startswith('[') & df_final_data3['code_lang'].str.endswith(']'))]
df_final_data3.to_csv('final_data4.csv', index=False)
print("DataFrame 'df_final_data3' saved to 'final_data4.csv'")

DataFrame 'df_final_data3' saved to 'final_data4.csv'

In [66]:
# 앞서 추출한 것들을 final_data2.csv에 병합 하면서 새롭게 final_data3.csv 만들기
df_final_data2 = pd.read_csv("final_data2.csv")
df_pluts = pd.read_csv("plutsyoutube_summaries_texts.csv")

df_merged = pd.concat([df_final_data2, df_pluts], ignore_index=True)
df_merged.to_csv('final_data3.csv', index=False)
print("DataFrame 'df_merged' saved to 'final_data3.csv'")

DataFrame 'df_merged' saved to 'final_data3.csv'

In [70]:
# final_data4.csv 의 categories 컬럼 안에 있는 내용을 같은 row의 category 컬럼 안에 대체하기
df_final_data4 = pd.read_csv("final_data4.csv")
df_final_data4['category'] = df_final_data4['categories']  
df_final_data4.to_csv('final_data4.csv', index=False)
print("DataFrame 'df_final_data4' updated 'category' column from 'categories' and saved to 'final_data4.csv'")

DataFrame 'df_final_data4' updated 'category' column from 'categories' and saved to 'final_data4.csv'

In [71]:
# categories랑 video_id 컬럼 삭제하기
df_final_data4 = pd.read_csv("final_data4.csv")
df_final_data4 = df_final_data4.drop(columns=['categories', 'video_id'])
df_final_data4.to_csv('final_data4.csv', index=False)
print("DataFrame 'df_final_data4' saved to 'final_data4.csv' after dropping 'categories' and 'video_id' columns.")

DataFrame 'df_final_data4' saved to 'final_data4.csv' after dropping 'categories' and 'video_id' columns.

In [72]:
# domain 컬럼이 빈 값이면 algorithm 으로 채우기
df = pd.read_csv("final_data4.csv")
df['domain'].fillna('algorithm', inplace=True)
df.to_csv('final_data4.csv', index=False)
print("DataFrame 'df' saved to 'final_data4.csv' after filling empty 'domain' values with 'algorithm'")

DataFrame 'df' saved to 'final_data4.csv' after filling empty 'domain' values with 'algorithm'

C:\Users\Playdata\AppData\Local\Temp\ipykernel_1576\276517136.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['domain'].fillna('algorithm', inplace=True)

In [73]:
# row 순서 바꾸기
# algorithm domain이 먼저 오고 livecoding domain이 나중에 오도록 변경
# domain이 livecoding인 row들 순서 바꾸면 안됨 그대로 유지하기
df = pd.read_csv("final_data4.csv")
df_algorithm = df[df['domain'] == 'algorithm']
df_livecoding = df[df['domain'] == 'livecoding']

# algorithm domain이 먼저 오고 livecoding domain이 나중에 오도록 변경
df_reordered = pd.concat([df_algorithm, df_livecoding], ignore_index=True)

# 저장
df_reordered.to_csv('final_data4.csv', index=False)
print("DataFrame 'df_reordered' saved to 'final_data4.csv' with reordered rows")

DataFrame 'df_reordered' saved to 'final_data4.csv' with reordered rows

In [74]:
# 지금 있는final_data4.csv 파일에 interview_final_data.csv 파일 병합하기
df_final_data4 = pd.read_csv("final_data4.csv")
df_interview = pd.read_csv("interview_final_data.csv")
df_merged = pd.concat([df_final_data4, df_interview], ignore_index=True)
df_merged.to_csv('final_data5.csv', index=False)
print("DataFrame 'df_merged' saved to 'final_data5.csv'")

DataFrame 'df_merged' saved to 'final_data5.csv'

In [75]:
# id 컬럼 초기화하고 다시 순서대로 매기기
df_final_data5 = pd.read_csv("final_data5.csv")
df_final_data5 = df_final_data5.reset_index(drop=True)
df_final_data5 = df_final_data5.reset_index(drop=True)
df_final_data5['id'] = df_final_data5.index + 1
df_final_data5.to_csv('final_data5.csv', index=False)
print("DataFrame 'df_final_data5' saved to 'final_data5.csv' with reset 'id' column.")

DataFrame 'df_final_data5' saved to 'final_data5.csv' with reset 'id' column.

In [76]:
#final_data3.csv에서 137번째까지의 row의 category 컬럼 값을 final_data5.csv의 category 컬럼 값으로 대체하기
df_final_data3 = pd.read_csv("final_data3.csv")
df_final_data5 = pd.read_csv("final_data5.csv")
df_final_data3_subset = df_final_data3.loc[:136, 'category']
df_final_data5.loc[:136, 'category'] = df_final_data3_subset
df_final_data5.to_csv('final_data5.csv', index=False)
print("DataFrame 'df_final_data5' saved to 'final_data6.csv' after updating 'category' column for first 137 rows")

DataFrame 'df_final_data5' saved to 'final_data6.csv' after updating 'category' column for first 137 rows

In [77]:
#final_data5.csv에서 category 컬럼 안에 있는 값들이 []로 감싸져 있지 않은 경우 []로 감싸지도록 변경하기
df_final_data5 = pd.read_csv("final_data5.csv")
def ensure_list_format(category_value):
    if isinstance(category_value, str) and not (category_value.startswith('[') and category_value.endswith(']')):
        return f"['{category_value}']"
    return category_value
df_final_data5['category'] = df_final_data5['category'].apply(ensure_list_format)
df_final_data5.to_csv('final_data5.csv', index=False)
print("DataFrame 'df_final_data5' saved to 'final_data5.csv' after updating 'category' column format")

DataFrame 'df_final_data5' saved to 'final_data5.csv' after updating 'category' column format